version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: food_agent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  food-agent-api:
    build: .
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: food_agent
      DB_SSL_MODE: disable
      JWT_ACCESS_SECRET: your-super-secret-access-key-change-this-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-this-in-production
      JWT_ACCESS_EXPIRATION: 15m
      JWT_REFRESH_EXPIRATION: 168h
      SERVER_PORT: 8888
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.env:/root/.env:ro

volumes:
  postgres_data: